### ISSUE TITLE
Node.js/sample01をWin＋Vagrantで実行するとエラーになる（MacはOK）

### ISSUE THREAD

**Issue by imaizm** [imaizm/VagrantEnv01#1]
エラーログ

```
==> default: ================================================================================
==> default: Error executing action `run` on resource 'bash[npm install for sample_01]'
==> default: ================================================================================
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '185'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150527-3572-3em7jv" ----
==> default: STDOUT: Now using node v0.12.2 (npm v2.7.4)
==> default: STDERR: npm WARN package.json chatrooms@0.0.1 No repository field.
==> default: npm WARN package.json chatrooms@0.0.1 No README data
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path ../uglify-js/bin/uglifyjs
==> default: npm ERR! code EPROTO
==> default: npm ERR! errno -71
==> default: npm ERR! EPROTO, symlink '../uglify-js/bin/uglifyjs'
==> default: npm ERR!
==> default: npm ERR! If you need help, you may report this error at:
==> default: npm ERR!     <https://github.com/npm/npm/issues>
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path npm-debug.log.3ad427f4a70bace75e285b15e8fdfbda
==> default: npm ERR! code ETXTBSY
==> default: npm ERR! errno -26
==> default: npm ERR! ETXTBSY, rename 'npm-debug.log.3ad427f4a70bace75e285b15e8fdfbda'
==> default: npm ERR!
==> default: npm ERR! If you need help, you may report this error at:
==> default: npm ERR!     <https://github.com/npm/npm/issues>
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /var/www/src/node.js_sample_01/npm-debug.log
==> default: ---- End output of "bash"  "/tmp/chef-script20150527-3572-3em7jv" ----
==> default: Ran "bash"  "/tmp/chef-script20150527-3572-3em7jv" returned 185
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/node.js/recipes/sample_01.rb
==> default:   5: bash "npm install for sample_01" do
==> default:   6:       code <<-EOH
==> default:   7:               . /usr/local/nvm/nvm.sh
==> default:   8:               nvm use v#{node.version}
==> default:   9:               cd /var/www/src/node.js_sample_01
==> default:  10:               npm install
==> default:  11:       EOH
==> default:  12: #     action :nothing
==> default:  13: #     subscribes :run, "bash[nvm.sh]", :delayed
==> default:  14: end
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/node.js/recipes/sample_01.rb:5:in `from_file'
==> default: bash("npm install for sample_01") do
==> default:   action "run"
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   command "npm install for sample_01"
==> default:   backup 5
==> default:   returns 0
==> default:   code "\t\t. /usr/local/nvm/nvm.sh\n\t\tnvm use v0.12.2\n\t\tcd /var/www/src/node.js_sample_01\n\t\tnpm install\n"
==> default:   interpreter "bash"
==> default:   declared_type :bash
==> default:   cookbook_name :"node.js"
==> default:   recipe_name "sample_01"
==> default: end
==> default: [2015-05-27T17:42:24+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-05-27T17:42:24+00:00] INFO: [bash[nvm.sh]] sending run action to bash[grunt] (delayed)
==> default: [2015-05-27T17:43:19+00:00] INFO: bash[grunt] ran successfully
==> default: [2015-05-27T17:43:19+00:00] INFO: [bash[nvm.sh]] sending run action to bash[gulp] (delayed)
==> default: [2015-05-27T17:48:30+00:00] INFO: bash[gulp] ran successfully
==> default: [2015-05-27T17:48:30+00:00] ERROR: Running exception handlers
==> default: [2015-05-27T17:48:30+00:00] ERROR: Exception handlers complete
==> default: [2015-05-27T17:48:30+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-05-27T17:48:30+00:00] ERROR: bash[npm install for sample_01] (node.js::sample_01 line 5) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '185'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150527-3572-3em7jv" ----
==> default: STDOUT: Now using node v0.12.2 (npm v2.7.4)
==> default: STDERR: npm WARN package.json chatrooms@0.0.1 No repository field.
==> default: npm WARN package.json chatrooms@0.0.1 No README data
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path ../uglify-js/bin/uglifyjs
==> default: npm ERR! code EPROTO
==> default: npm ERR! errno -71
==> default:
==> default: npm ERR! EPROTO, symlink '../uglify-js/bin/uglifyjs'
==> default: npm ERR!
==> default: npm ERR! If you need help, you may report this error at:
==> default: npm ERR!     <https://github.com/npm/npm/issues>
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path npm-debug.log.3ad427f4a70bace75e285b15e8fdfbda
==> default: npm ERR! code ETXTBSY
==> default: npm ERR! errno -26
==> default:
==> default: npm ERR! ETXTBSY, rename 'npm-debug.log.3ad427f4a70bace75e285b15e8fdfbda'
==> default: npm ERR!
==> default: npm ERR! If you need help, you may report this error at:
==> default: npm ERR!     <https://github.com/npm/npm/issues>
==> default:
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /var/www/src/node.js_sample_01/npm-debug.log
==> default: ---- End output of "bash"  "/tmp/chef-script20150527-3572-3em7jv" ----
==> default: Ran "bash"  "/tmp/chef-script20150527-3572-3em7jv" returned 185
==> default: [2015-05-27T17:48:30+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by imaizm** [comment]
bash[npm install for sample_01]の実行者をvagrantにした場合のエラーログ

```
==> default: ================================================================================
==> default: Error executing action `run` on resource 'bash[npm install for sample_01]'
==> default: ================================================================================
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '243'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150529-3572-1cc02ue" ----
==> default: STDOUT: Now using node v0.12.2 (npm v2.7.4)
==> default: STDERR: npm WARN package.json chatrooms@0.0.1 No repository field.
==> default: npm WARN package.json chatrooms@0.0.1 No README data
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path /root/.npm
==> default: npm ERR! code EACCES
==> default: npm ERR! errno -13
==> default: npm ERR! Error: EACCES, mkdir '/root/.npm'
==> default: npm ERR!     at Error (native)
==> default: npm ERR!  { [Error: EACCES, mkdir '/root/.npm']
==> default: npm ERR!   errno: -13,
==> default: npm ERR!   code: 'EACCES',
==> default: npm ERR!   path: '/root/.npm',
==> default: npm ERR!   parent: 'chatrooms' }
==> default: npm ERR!
==> default: npm ERR! Please try running this command again as root/Administrator.
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path npm-debug.log.b36fd66de42ebad5d7ea24bf84247005
==> default: npm ERR! code ETXTBSY
==> default: npm ERR! errno -26
==> default: npm ERR! ETXTBSY, rename 'npm-debug.log.b36fd66de42ebad5d7ea24bf84247005'
==> default: npm ERR!
==> default: npm ERR! If you need help, you may report this error at:
==> default: npm ERR!     <https://github.com/npm/npm/issues>
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /var/www/src/node.js_sample_01/npm-debug.log
==> default: ---- End output of "bash"  "/tmp/chef-script20150529-3572-1cc02ue" ----
==> default: Ran "bash"  "/tmp/chef-script20150529-3572-1cc02ue" returned 243
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/node.js/recipes/sample_01.rb
==> default:   5: bash "npm install for sample_01" do
==> default:   6:       user "vagrant"
==> default:   7:       group "vagrant"
==> default:   8:       code <<-EOH
==> default:   9:               . /usr/local/nvm/nvm.sh
==> default:  10:               nvm use v#{node.version}
==> default:  11:               cd /var/www/src/node.js_sample_01
==> default:  12:               npm install
==> default:  13:       EOH
==> default:  14: #     action :nothing
==> default:  15: #     subscribes :run, "bash[nvm.sh]", :delayed
==> default:  16: end
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/node.js/recipes/sample_01.rb:5:in `from_file'
==> default: bash("npm install for sample_01") do
==> default:   action "run"
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   command "npm install for sample_01"
==> default:   backup 5
==> default:   group "vagrant"
==> default:   returns 0
==> default:   user "vagrant"
==> default:   code "\t\t. /usr/local/nvm/nvm.sh\n\t\tnvm use v0.12.2\n\t\tcd /var/www/src/node.js_sample_01\n\t\tnpm install\n"
==> default:   interpreter "bash"
==> default:   declared_type :bash
==> default:   cookbook_name :"node.js"
==> default:   recipe_name "sample_01"
==> default: end
==> default:
==> default: [2015-05-29T10:34:19+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-05-29T10:34:19+00:00] INFO: [bash[nvm.sh]] sending run action to bash[grunt] (delayed)
==> default: [2015-05-29T10:35:14+00:00] INFO: bash[grunt] ran successfully
==> default: [2015-05-29T10:35:14+00:00] INFO: [bash[nvm.sh]] sending run action to bash[gulp] (delayed)
==> default: [2015-05-29T10:40:23+00:00] INFO: bash[gulp] ran successfully
==> default: [2015-05-29T10:40:23+00:00] ERROR: Running exception handlers
==> default: [2015-05-29T10:40:23+00:00] ERROR: Exception handlers complete
==> default: [2015-05-29T10:40:23+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-05-29T10:40:24+00:00] ERROR: bash[npm install for sample_01] (node.js::sample_01 line 5) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '243'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150529-3572-1cc02ue" ----
==> default: STDOUT: Now using node v0.12.2 (npm v2.7.4)
==> default: STDERR: npm WARN package.json chatrooms@0.0.1 No repository field.
==> default: npm WARN package.json chatrooms@0.0.1 No README data
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path /root/.npm
==> default: npm ERR! code EACCES
==> default: npm ERR! errno -13
==> default:
==> default: npm ERR! Error: EACCES, mkdir '/root/.npm'
==> default: npm ERR!     at Error (native)
==> default: npm ERR!  { [Error: EACCES, mkdir '/root/.npm']
==> default: npm ERR!   errno: -13,
==> default: npm ERR!   code: 'EACCES',
==> default: npm ERR!   path: '/root/.npm',
==> default: npm ERR!   parent: 'chatrooms' }
==> default: npm ERR!
==> default: npm ERR! Please try running this command again as root/Administrator.
==> default: npm ERR! Linux 2.6.32-431.3.1.el6.x86_64
==> default: npm ERR! argv "/usr/local/nvm/versions/node/v0.12.2/bin/node" "/usr/local/nvm/versions/node/v0.12.2/bin/npm" "install"
==> default: npm ERR! node v0.12.2
==> default: npm ERR! npm  v2.7.4
==> default: npm ERR! path npm-debug.log.b36fd66de42ebad5d7ea24bf84247005
==> default: npm ERR! code ETXTBSY
==> default: npm ERR! errno -26
==> default:
==> default: npm ERR! ETXTBSY, rename 'npm-debug.log.b36fd66de42ebad5d7ea24bf84247005'
==> default: npm ERR!
==> default: npm ERR! If you need help, you may report this error at:
==> default: npm ERR!     <https://github.com/npm/npm/issues>
==> default:
==> default: npm ERR! Please include the following file with any support request:
==> default: npm ERR!     /var/www/src/node.js_sample_01/npm-debug.log
==> default: ---- End output of "bash"  "/tmp/chef-script20150529-3572-1cc02ue" ----
==> default: Ran "bash"  "/tmp/chef-script20150529-3572-1cc02ue" returned 243
==> default: [2015-05-29T10:40:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessf
ully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by imaizm** [comment]
■対応方法
「npm install」コマンドに「--no-bin-links」オプションを付ける。

■理由
Vagrant(Virtual Box)の共有フォルダはホストOSのフォルダであるため、ホストOSがWindowsの場合、シンボリックリンク(symlink)をサポートしていないからエラーが出る

(参考)
http://eiua-memo.tumblr.com/post/117361529158/npm-vagrant-vagrant-npm
